"""Optional step — MM/PBSA & MM/GBSA binding free energy (ΔG) via gmx_MMPBSA.

This is the quantitative "does it bind, and how strongly?" metric — directly comparable to
experiment (ΔG ≈ -RT·ln Kd) in a way RMSD/contacts are not. It is OPT-IN
(job ``compute_mmpbsa: true``) and only meaningful when the ligand stays BOUND over the
analysed window, so it is intended for the production 50/100 ns runs, not a short test where
the pose dissociates. It runs over the existing GROMACS production trajectory (md.xtc/.tpr/
topol.top/index.ndx) using the receptor (Protein) and ligand (MOL) index groups.

Requirements (lab gmx_env): gmx_MMPBSA + AmberTools (sander, MMPBSA.py, cpptraj) + an MPI
runtime (gmx_MMPBSA imports mpi4py at startup). If gmx_MMPBSA is unavailable or fails, the
step logs a clear, actionable message and is skipped WITHOUT failing the job — the geometric
analysis (analyze_md) still stands.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


def _index_groups(ndx: Path) -> List[str]:
    """Return index.ndx group names in their numeric order (0-based)."""
    groups: List[str] = []
    for line in ndx.read_text(errors="replace").splitlines():
        m = re.match(r"\s*\[\s*(.+?)\s*\]\s*$", line)
        if m:
            groups.append(m.group(1))
    return groups


def _resolve_groups(ndx: Path) -> Tuple[Optional[int], Optional[int]]:
    """Resolve (receptor_group_index, ligand_group_index) — Protein + MOL — 0-based."""
    groups = _index_groups(ndx)
    rec = next((i for i, g in enumerate(groups) if g == "Protein"), None)
    lig = next((i for i, g in enumerate(groups) if g in ("MOL", "LIG")), None)
    return rec, lig


def _xtc_frame_count(xtc: Path) -> int:
    """Exact number of frames in md.xtc via ``gmx check`` (0 if it can't be determined).

    Used to map a bound *fraction* of the trajectory onto 1-based md.xtc frame indices, which
    avoids guessing whether frame 1 is t=0 or t=Δ and the engine's n_xtc off-by-one.
    """
    gmx = shutil.which("gmx") or shutil.which("gmx_mpi")
    if not gmx or not xtc.exists():
        return 0
    try:
        proc = subprocess.run([gmx, "check", "-f", str(xtc)],
                              capture_output=True, text=True, timeout=900)
    except Exception:  # noqa: BLE001
        return 0
    text = (proc.stdout or "") + (proc.stderr or "")
    m = re.search(r"Coords\s+(\d+)", text)            # "Coords   1001   10"
    if m:
        return int(m.group(1))
    m = re.search(r"Last frame\s+(\d+)", text)         # 0-based last frame index
    if m:
        return int(m.group(1)) + 1
    return 0


def _bound_endframe(ctx, settings, md: Dict[str, Any], n_xtc: int) -> Tuple[Optional[int], Optional[float]]:
    """Map analyze_md's bound window (in ns) onto a 1-based md.xtc end frame.

    Returns (endframe, end_ns). Uses the bound *fraction* of the run (end_ns / md_length_ns)
    times the real xtc frame count, so it is robust to trajectory_output_ps / step-0 details.
    Falls back to trajectory_output_ps timing when the xtc frame count is unavailable. Returns
    (None, end_ns) if no usable bound window is present.
    """
    summ = ctx.analysis_dir / "summary.json"
    if not summ.exists():
        return None, None
    try:
        data = json.loads(summ.read_text(errors="replace"))
    except Exception:  # noqa: BLE001
        return None, None
    bw = data.get("bound_window")
    if not isinstance(bw, dict):
        return None, None
    end_ns = bw.get("end_ns")
    md_len = data.get("md_length_ns") or md.get("completed_ns")
    if bw.get("fully_bound") and n_xtc:
        return n_xtc, end_ns
    if not end_ns or not md_len or float(md_len) <= 0:
        return None, end_ns
    frac = max(0.0, min(1.0, float(end_ns) / float(md_len)))
    if n_xtc:
        # 1-based inclusive: frame 1 <-> t=0, frame n_xtc <-> t=md_length, so the time span
        # covers (n_xtc - 1) intervals. floor(frac*(n_xtc-1))+1 always lands in [1, n_xtc].
        return min(n_xtc, int(frac * (n_xtc - 1)) + 1), end_ns
    tps = float(getattr(settings, "trajectory_output_ps", 0) or 0)
    if tps > 0:
        return max(1, round(float(end_ns) * 1000.0 / tps) + 1), end_ns
    return None, end_ns


def _mmpbsa_in(startframe: int, endframe: int, interval: int, salt: float) -> str:
    """gmx_MMPBSA input: single-trajectory MM/GBSA (igb=5) + MM/PBSA (Poisson-Boltzmann).

    GBSA is fast and good for ranking; PB is slower but the more rigorous continuum model.
    Both reported so the user can compare. Entropy is omitted (interaction-energy ΔG), which
    is standard for relative ranking and what most published peptide/ligand MM-PBSA uses.
    """
    return (
        "Auto-generated by MD Platform — single-trajectory MM/PBSA + MM/GBSA\n"
        "&general\n"
        f'  sys_name="prot-lig", startframe={startframe}, endframe={endframe}, '
        f"interval={interval},\n"
        '  forcefields="oldff/leaprc.ff14SB,leaprc.gaff2", PBRadii=3,\n'
        "/\n"
        "&gb\n"
        f"  igb=5, saltcon={salt:.3f},\n"
        "/\n"
        "&pb\n"
        f"  istrng={salt:.3f}, fillratio=4.0, radiopt=0,\n"
        "/\n"
        "&decomp\n"
        # Per-residue decomposition (idecomp=1): each receptor residue's ΔG contribution to
        # binding — answers "which peptide residues are important for binding".
        "  idecomp=1, dec_verbose=0,\n"
        "/\n"
    )


def _parse_decomp(decomp_dat: Path) -> List[Dict[str, Any]]:
    """Parse per-residue ΔG contributions from FINAL_DECOMP_MMPBSA.dat.

    Returns receptor (peptide) residues in sequence order:
    [{chain, resname, resnum, total_dg, vdw, eel, polar}]. Rows look like
    ``R:A:CYS:2,<Internal avg>,sd,sem,<vdW avg>,...,<TOTAL avg>,sd,sem`` (6 components × 3 stats);
    we take each component's Avg. column. ``R:`` = receptor, ``L:`` = ligand (skipped)."""
    if not decomp_dat.exists():
        return []
    residues: List[Dict[str, Any]] = []
    seen: set = set()  # the .dat has GB and PB decomp sections; keep first (GB) per residue
    in_total = False
    for line in decomp_dat.read_text(errors="replace").splitlines():
        if line.startswith("Total Energy Decomposition:"):
            in_total = True
            continue
        if in_total and (line.startswith("Sidechain Energy") or line.startswith("Backbone Energy")):
            break  # only the per-residue TOTAL table is needed
        if not in_total or not line.startswith("R:"):
            continue
        parts = line.split(",")
        if len(parts) < 17:
            continue
        rid = parts[0].split(":")  # R:A:CYS:2
        if len(rid) < 4:
            continue

        def avg(i: int) -> float:
            try:
                return round(float(parts[i]), 4)
            except (ValueError, IndexError):
                return 0.0

        key = (rid[1], rid[3])  # (chain, resnum) — skip the duplicate PB-section rows
        if key in seen:
            continue
        seen.add(key)
        residues.append({
            "chain": rid[1], "resname": rid[2], "resnum": int(rid[3]) if rid[3].isdigit() else rid[3],
            "internal": avg(1), "vdw": avg(4), "eel": avg(7), "polar": avg(10),
            "nonpolar": avg(13), "total_dg": avg(16),
        })
    residues.sort(key=lambda r: r["resnum"] if isinstance(r["resnum"], int) else 0)
    return residues


def _write_per_residue_plot(plots_dir: Path, residues: List[Dict[str, Any]]) -> None:
    """Bar chart of per-residue ΔG along the peptide sequence (favorable = negative = green)."""
    labels = [f"{r['resname']}{r['resnum']}" for r in residues]
    vals = [r["total_dg"] for r in residues]
    colors = ["#2ca02c" if v < 0 else "#d62728" for v in vals]  # green favorable, red unfavorable
    fig = {
        "data": [{"x": labels, "y": vals, "type": "bar", "name": "ΔG contribution",
                  "marker": {"color": colors}}],
        "layout": {
            "title": {"text": "Per-residue binding ΔG contribution (peptide)"},
            "xaxis": {"title": {"text": "Residue"}},
            "yaxis": {"title": {"text": "ΔG contribution (kcal/mol)"}},
            "margin": {"l": 60, "r": 20, "t": 50, "b": 50}, "template": "plotly_white",
        },
    }
    plots_dir.mkdir(parents=True, exist_ok=True)
    (plots_dir / "per_residue.json").write_text(json.dumps(fig))


def _parse_dg(results_dat: Path) -> Dict[str, Any]:
    """Parse ΔTOTAL (binding ΔG, kcal/mol) for GB and PB from FINAL_RESULTS_MMPBSA.dat."""
    out: Dict[str, Any] = {}
    if not results_dat.exists():
        return out
    text = results_dat.read_text(errors="replace")
    # Sections look like "GENERALIZED BORN:" ... "DELTA TOTAL  <val> <sd> ..." and
    # "POISSON BOLTZMANN:" ... likewise. Capture the DELTA TOTAL under each method.
    for method, key in (("GENERALIZED BORN", "gbsa_dg_kcal_mol"), ("POISSON BOLTZMANN", "pbsa_dg_kcal_mol")):
        block = text.split(method, 1)
        if len(block) < 2:
            continue
        seg = block[1]
        # The BINDING ΔG is the "ΔTOTAL" under "Delta (Complex - Receptor - Ligand)" — NOT the
        # plain "TOTAL" lines (those are the absolute energies of the complex/receptor/ligand,
        # which are huge). Scope to the Delta subsection and require the Δ (or ASCII "DELTA").
        delta = re.split(r"Delta\s*\(Complex", seg, maxsplit=1)
        scope = delta[1] if len(delta) > 1 else seg
        m = re.search(r"(?:ΔTOTAL|DELTA\s+TOTAL)\s+([-+]?\d+\.\d+)", scope)
        if m:
            out[key] = float(m.group(1))
    return out


def run(ctx, settings, *, md: Dict[str, Any]) -> Dict[str, Any]:
    step = "mmpbsa"
    if not ctx.job_meta.get("compute_mmpbsa"):
        return {"skipped": True, "reason": "compute_mmpbsa not requested"}

    ctx.set_status("analyzing", current_step=step, progress=95.0)
    gmx_mmpbsa = shutil.which("gmx_MMPBSA")
    md_dir = ctx.md_dir
    tpr, xtc = md_dir / "md.tpr", md_dir / "md.xtc"
    top, ndx = md_dir / "topol.top", md_dir / "index.ndx"

    missing = [p.name for p in (tpr, xtc, top, ndx) if not p.exists()]
    if not gmx_mmpbsa or missing:
        reason = (
            "gmx_MMPBSA not on PATH" if not gmx_mmpbsa
            else f"missing GROMACS outputs: {missing}"
        )
        ctx.warning(step, f"MM/PBSA skipped ({reason}). Binding ΔG not computed; geometric "
                          "analysis is unaffected. Install gmx_MMPBSA + an MPI runtime to enable.")
        return {"skipped": True, "reason": reason}

    rec, lig = _resolve_groups(ndx)
    if rec is None or lig is None:
        ctx.warning(step, "MM/PBSA skipped: could not resolve Protein/MOL index groups.")
        return {"skipped": True, "reason": "groups unresolved"}

    n_frames = int(md.get("n_frames") or 0)
    n_xtc = _xtc_frame_count(xtc)
    # Frame window (1-based into md.xtc). Honor an explicit job override; otherwise restrict
    # the binding-ΔG window to the bound segment detected by analyze_md — frames after the
    # ligand dissociates would corrupt MM/PBSA. Subsample to ~50 frames to keep PB tractable.
    startframe = int(ctx.job_meta.get("mmpbsa_startframe", 1))
    explicit_end = ctx.job_meta.get("mmpbsa_endframe")
    bound_end_ns: Optional[float] = None
    window_basis = "explicit job override"
    if explicit_end is not None:
        endframe = int(explicit_end)
    else:
        endframe, bound_end_ns = _bound_endframe(ctx, settings, md, n_xtc)
        if endframe is None:
            endframe = max(startframe, n_xtc or n_frames or 1)
            window_basis = "full trajectory (no bound window detected)"
        else:
            window_basis = "auto-detected bound window (ligand RMSD)"
    if n_xtc:
        endframe = min(endframe, n_xtc)
    endframe = max(startframe, endframe)
    interval = max(1, (endframe - startframe + 1) // 50)
    salt = float(ctx.job_meta.get("salt_concentration", 0.15))

    work = ctx.analysis_dir / "mmpbsa"
    work.mkdir(parents=True, exist_ok=True)
    (work / "mmpbsa.in").write_text(_mmpbsa_in(startframe, endframe, interval, salt))
    results_dat = work / "FINAL_RESULTS_MMPBSA.dat"

    cmd = [
        gmx_mmpbsa, "-O", "-nogui",
        "-i", str(work / "mmpbsa.in"),
        "-cs", str(tpr), "-ci", str(ndx), "-cg", str(rec), str(lig),
        "-ct", str(xtc), "-cp", str(top),
        "-o", str(results_dat), "-eo", str(work / "FINAL_RESULTS_MMPBSA.csv"),
        "-do", str(work / "FINAL_DECOMP_MMPBSA.dat"), "-deo", str(work / "FINAL_DECOMP_MMPBSA.csv"),
    ]
    win_note = f" [{window_basis}" + (f", ≤{bound_end_ns:g} ns]" if bound_end_ns is not None else "]")
    ctx.info(step, f"Computing binding ΔG (MM/GBSA igb=5 + MM/PBSA) over md.xtc frames "
                   f"{startframe}-{endframe}:{interval} of {n_xtc or '?'}{win_note} "
                   f"(receptor grp {rec}, ligand grp {lig}).")
    ctx.info(step, "$ " + " ".join(cmd))
    try:
        proc = subprocess.run(cmd, cwd=str(work), capture_output=True, text=True, timeout=7200)
    except Exception as exc:  # noqa: BLE001
        ctx.warning(step, f"MM/PBSA execution error: {exc}. Skipped (geometric analysis unaffected).")
        return {"skipped": True, "reason": f"exec error: {exc}"}
    if proc.returncode != 0:
        tail = (proc.stdout or "")[-400:] + (proc.stderr or "")[-400:]
        ctx.warning(step, f"gmx_MMPBSA exited {proc.returncode}; ΔG not computed. Tail: {tail[:400]}")
        return {"skipped": True, "reason": f"gmx_MMPBSA rc={proc.returncode}"}

    dg = _parse_dg(results_dat)
    # Pose occupancy from analyze_md (fraction of the trajectory the ligand stayed bound):
    # a single-trajectory, entropy-free MM/GBSA number is only meaningful if the complex was
    # actually bound, so we carry occupancy + a reliability flag into the result.
    occ = None
    try:
        s = json.loads((ctx.analysis_dir / "summary.json").read_text())
        occ = (s.get("bound_window") or {}).get("pose_occupancy")
    except Exception:  # noqa: BLE001
        pass
    summary = {
        "method": "MM/GBSA(igb5) + MM/PBSA, single-trajectory, no entropy",
        # Factual flag: this number is a relative ranking score, not an absolute ΔG/Kd. The UI and
        # docs carry the full interpretation; here we just record the policy so consumers don't
        # mislabel it.
        "score_type": "relative_ranking",
        "frames": f"{startframe}-{endframe}:{interval}",
        "window_basis": window_basis,
        "pose_occupancy": occ,
        "reliable": (occ is not None and occ >= 0.5),
        "receptor_group": rec, "ligand_group": lig,
        **dg,
    }
    if occ is not None and occ < 0.5:
        summary["warning"] = f"pose_occupancy {occ:.2f} < 0.5: ligand not reliably bound; score unreliable"
    if bound_end_ns is not None:
        summary["bound_window_ns"] = [0.0, round(float(bound_end_ns), 4)]
    (ctx.analysis_dir / "mmpbsa.json").write_text(json.dumps(summary, indent=2))

    # Per-residue decomposition → which peptide residues drive binding.
    residues = _parse_decomp(work / "FINAL_DECOMP_MMPBSA.dat")
    if residues:
        hotspots = sorted(residues, key=lambda r: r["total_dg"])[:5]  # most favorable first
        per_res = {
            "method": "MM/GBSA per-residue decomposition (idecomp=1, kcal/mol)",
            "frames": summary["frames"],
            "window_basis": window_basis,
            "residues": residues,
            "hotspots": [{"residue": f"{h['resname']}{h['resnum']}", "total_dg": h["total_dg"]}
                         for h in hotspots if h["total_dg"] < 0],
        }
        (ctx.analysis_dir / "per_residue.json").write_text(json.dumps(per_res, indent=2))
        _write_per_residue_plot(ctx.plots_dir, residues)
        summary["per_residue_count"] = len(residues)
        ctx.info(step, "Per-residue decomposition written for "
                       f"{len(residues)} peptide residues; top hotspots: "
                       + ", ".join(f"{h['resname']}{h['resnum']}({h['total_dg']:+.1f})" for h in hotspots[:3]))

    gb = dg.get("gbsa_dg_kcal_mol"); pb = dg.get("pbsa_dg_kcal_mol")
    ctx.info(step, f"Binding ΔG — MM/GBSA: {gb if gb is not None else 'n/a'} kcal/mol, "
                   f"MM/PBSA: {pb if pb is not None else 'n/a'} kcal/mol.")
    return {"skipped": False, **summary}
